// Copy and numbers for the public site (landing + nav + footer). Every
// figure here is a naano marketing claim copied from the product map, not a
// measurement from our database. Per-page copy lives in page-copy.ts and
// benchmarks-data.ts.

export const NAV_LINKS = [
  { href: "/", label: "For companies" },
  { href: "/for-creators", label: "For creators" },
  { href: "/for-agencies", label: "For agencies" },
  { href: "/#how-it-works", label: "How it works" },
  { href: "/benchmarks", label: "Resources" },
] as const;

export const FOOTER_COLUMNS = [
  {
    heading: "Product",
    links: [
      { href: "/#how-it-works", label: "Features" },
      { href: "/pricing", label: "Pricing" },
      { href: "/faq", label: "FAQs" },
      { href: "/benchmarks", label: "Reports & benchmarks" },
      { href: "/about", label: "About" },
    ],
  },
  {
    heading: "Company",
    links: [
      { href: "/about", label: "About us" },
      { href: "/for-agencies", label: "For agencies" },
      { href: "/login", label: "Sign in" },
      { href: "/register", label: "Create an account" },
    ],
  },
  {
    heading: "For AI agents",
    links: [
      { href: "/pricing", label: "pricing.md" },
      { href: "/benchmarks", label: "Reports & data" },
    ],
  },
  {
    heading: "Press",
    links: [
      { href: "/case-study", label: "BlogSEO case study" },
      { href: "/about", label: "Founders" },
    ],
  },
  {
    heading: "Resources",
    links: [
      { href: "/benchmarks", label: "Q2 2026 benchmark report" },
      { href: "/for-creators", label: "Get paid to post on LinkedIn" },
      { href: "/case-study", label: "Creator-led growth for B2B" },
      { href: "/faq", label: "Creator marketplace explained" },
    ],
  },
] as const;

export const FOOTER_TAGLINE = "Turn LinkedIn creators into your best acquisition channel.";

export const HERO = {
  badge: "Where B2B brands work with creators",
  title: "The B2B LinkedIn Creator Marketplace.",
  sub: "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
  primary: { href: "/register/brand", label: "Launch a campaign" },
  secondary: { href: "/#how-it-works", label: "See how Naano works" },
  trust: "Trusted by modern B2B teams",
} as const;

// Text wordmarks only: naano's logo strip uses image assets we do not ship.
export const HERO_LOGOS = ["gojiberry", "ChatSEO", "Abyssale", "BlogSEO", "lemlist", "folk.", "LEADBAY"] as const;

export const LOGO_WALL = [
  "lemlist",
  "folk.",
  "LEADBAY",
  "ringover",
  "attio",
  "La Growth Machine",
  "gojiberry",
  "ChatSEO",
  "Abyssale",
] as const;
export const LOGO_WALL_MORE = "+30";

export const QUOTE = {
  brand: "Zmirov Communication",
  text: "We manage €10M+ of influence budget every year. For B2B, Naano simply makes our life",
  highlight: "easier",
  author: "David Zmirov",
  role: "CEO, Zmirov Communication",
  kind: "Influence agency",
} as const;

export const SHOWCASE = {
  eyebrow: "The Naano creator marketplace",
  title: "Work with all the best creators.",
  sub: "Find the right B2B voices, compare their audience fit, and book every collaboration from one place.",
  stats: [
    { title: "3,000+ vetted creators", body: "Specialist B2B voices, ready to collaborate.", kind: "avatars" },
    { title: "Across 100 countries", body: "Local expertise with genuinely global reach.", kind: "flags" },
    { title: "Matched to your buyers", body: "Audience fit comes before follower count.", kind: "match" },
  ],
  matchExample: { fit: "96%", label: "AI & SaaS creator", tags: ["Founders", "Sales leaders", "GTM teams"] },
  flags: ["🇫🇷", "🇺🇸", "🇩🇪", "🇬🇧", "🇪🇸", "🇨🇦", "🇳🇱"],
} as const;

// The showcase scores creators against one illustrative brief so the fit %
// on the public cards is a real fitScore() output, not a decoration.
export const SHOWCASE_BRIEF = {
  targetIndustries: ["B2B", "SaaS", "AI"],
  icpTitles: ["Founder / CEO of early-stage SaaS", "Head of Sales", "VP Marketing"],
} as const;
export const SHOWCASE_CANDIDATES = 120;
export const SHOWCASE_COUNT = 6;

export type PublicCreator = {
  id: string;
  name: string;
  industries: string[];
  country: string;
  headline: string;
  fit: number;
  followers: number;
  medianViews: number;
  priceCents: number;
  avatarUrl: string | null;
};

// Shown when DATABASE_URL is missing. Illustrative, clearly not seeded data.
export const STATIC_SHOWCASE_CREATORS: PublicCreator[] = [
  { id: "s1", name: "Aymane Junior", industries: ["AI", "SaaS"], country: "DE", headline: "Building intelligent systems that turn data into impact.", fit: 97, followers: 14_100, medianViews: 18_700, priceCents: 36_000, avatarUrl: null },
  { id: "s2", name: "Emma Guetta", industries: ["AI", "Media / Content"], country: "FR", headline: "Content strategist for B2B SaaS teams.", fit: 96, followers: 7_800, medianViews: 25_600, priceCents: 48_000, avatarUrl: null },
  { id: "s3", name: "Augustin Rudigoz", industries: ["Productivity", "Fintech"], country: "FR", headline: "Entrepreneurs, opérateurs, investisseurs.", fit: 92, followers: 14_000, medianViews: 11_200, priceCents: 96_000, avatarUrl: null },
  { id: "s4", name: "Raghav Jerath", industries: ["Growth / GTM", "Software"], country: "FR", headline: "Ex-YC operator writing about GTM.", fit: 90, followers: 2_400, medianViews: 2_100, priceCents: 8_400, avatarUrl: null },
  { id: "s5", name: "Daniel Meisen", industries: ["Growth / GTM", "Agencies", "Consulting"], country: "DE", headline: "Helping agencies scale outbound.", fit: 89, followers: 5_900, medianViews: 2_800, priceCents: 12_000, avatarUrl: null },
  { id: "s6", name: "Pierre Davadan", industries: ["SaaS", "AI"], country: "FR", headline: "VC Analyst Open CNP", fit: 89, followers: 4_200, medianViews: 2_200, priceCents: 8_400, avatarUrl: null },
];

export const HOW_IT_WORKS = {
  eyebrow: "One platform, from brief to results",
  title: "Run creator campaigns from one place.",
  sub: "Find the right voices, launch faster, and connect every post to measurable business results.",
  steps: [
    { n: "01", label: "Find creators your buyers trust" },
    { n: "02", label: "Build a campaign brief in minutes" },
    { n: "03", label: "Manage every collaboration" },
    { n: "04", label: "Track reach, clicks, and leads" },
    { n: "05", label: "Pay creators without the admin" },
  ],
  fitCards: [
    { name: "Eric", fit: "92%" },
    { name: "Robin", fit: "88%" },
    { name: "Aya", fit: "84%" },
  ],
  brief: { title: "Campaign brief", tag: "AI", items: ["Objectives and key messages", "Creator guidelines", "Tracking links ready"] },
  collaborations: [
    { name: "Raphael", status: "Draft ready" },
    { name: "Thomas", status: "Scheduled" },
    { name: "Nada", status: "Live" },
  ],
  tracking: { label: "Attributed pipeline", value: "€48.2K", delta: "+24%", views: "124K views", leads: "418 leads" },
  payout: { title: "Payment scheduled", sub: "Handled by Naano", label: "Creator payout", value: "€1,240", chips: ["Contract", "Invoice", "Payout"] },
} as const;

export const CASE_STUDY = {
  eyebrow: "Real teams. Measurable pipeline.",
  sub: "See how B2B teams turn creator trust into attributable demand with Naano.",
  videoLabel: "Video testimonial",
  duration: "2:40",
  quote: "Naano became one of our fastest acquisition channels. We know exactly what every creator brings.",
  author: "Vincent Josse",
  role: "CEO & Founder, BlogSEO",
  brand: "BlogSEO",
  title: "How BlogSEO turned creator content into product signups",
  body: "BlogSEO briefed SEO & SaaS creators on LinkedIn and X, then traced every trial back to the post that drove it, all in Naano.",
  stats: [
    { value: "9", label: "creators activated" },
    { value: "2,940", label: "qualified clicks" },
    { value: "512", label: "trials started" },
  ],
  link: { href: "/case-study", label: "Read case study" },
  logosHeading: "Trusted by teams at",
} as const;

export const RESULTS = {
  eyebrow: "The results",
  title: "Proven across thousands of campaigns.",
  stats: [
    { value: "5M+", label: "Impressions generated" },
    { value: "30K+", label: "Leads generated" },
    { value: "2,000+", label: "Creators on Naano" },
    { value: "5K+", label: "Posts published" },
  ],
} as const;

// naano's published Q2 2026 benchmarks. Clicks and leads on the post cards
// are estimates derived from real seeded impressions with these rates.
export const BENCHMARK_CTR = 0.12;
export const BENCHMARK_CPC_EUR = 2.3;
export const BENCHMARK_CPL_EUR = 18.1;
export const LEADS_PER_CLICK = BENCHMARK_CPC_EUR / BENCHMARK_CPL_EUR;
export const POST_EXAMPLES_COUNT = 4;

export type PublicPost = {
  id: string;
  url: string;
  title: string;
  creatorName: string;
  creatorLine: string;
  avatarUrl: string | null;
  impressions: number;
  clicksEst: number;
  leadsEst: number;
};

export const POST_EXAMPLES = {
  title: "Real posts from real creators.",
  sub: "Impressions are the creator's own LinkedIn numbers; clicks and leads are estimated from Naano's marketplace benchmarks.",
  cta: { href: "/register/brand", label: "Get started" },
  ctaNote: "Start free. Pay per post when you're ready.",
  estLabel: "est.",
} as const;

export const PRICING = {
  title: "Pricing.",
  sub: "Start free. Upgrade when you want your time back.",
  body: "Choose whether you want to run creator campaigns in-house or have Naano operate them.",
  footnote: "Campaign spend is separate. No lock-in. Cancel anytime.",
  plans: [
    {
      eyebrow: "Self-serve",
      title: "Run it yourself.",
      body: "For teams that want the infrastructure to run creator campaigns in-house.",
      price: "€0",
      priceNote: "/ month",
      priceDetail: "Pay per published post, from €20. No CPC, no CPM, no retainer.",
      features: ["Creator marketplace access", "AI-powered brief creation", "Track clicks, companies and pipeline", "Automatic creator payouts"],
      cta: { href: "/register/brand", label: "Start for free", primary: false },
    },
    {
      eyebrow: "Managed campaigns",
      title: "Get your time back.",
      body: "For teams that want Naano to operate their creator channel end to end.",
      price: "€700",
      priceNote: "/ month + post spend",
      priceDetail: "Flat fee. Custom quote for multi-brand or agency setups.",
      features: ["Campaign strategy and positioning", "Creator sourcing and coordination", "Brief creation and campaign launch", "Reporting and optimisation"],
      cta: { href: "/#cta", label: "Book a strategy call", primary: true },
    },
  ],
} as const;

export const FAQ = {
  title: "Frequently asked questions.",
  sub: "Everything you need to know before getting started.",
  contact: { href: "/#cta", label: "Talk to our team" },
  items: [
    {
      q: "What is Naano?",
      a: "Naano is a B2B LinkedIn creator marketplace: companies discover and book vetted creators for sponsored LinkedIn campaigns, each at a fixed price per post set by the creator. The marketplace spans creators from niche voices with around 1,000 followers to established B2B creators with audiences of several hundred thousand.",
    },
    {
      q: "How does Naano find the right creators?",
      a: "The matching engine scores every creator on audience fit, category relevance and engagement quality. Audience fit comes before follower count: a 3,000-follower creator whose comment section is full of your buyers ranks above a 100,000-follower generalist. Every match comes with a one-line reason why the creator belongs on your shortlist.",
    },
    {
      q: "Which platforms do you support?",
      a: "LinkedIn is the core network. Creators can also be booked for X and YouTube, and the matching engine reads signals across all three. Tracking links and attribution work the same way on every network.",
    },
    {
      q: "How does per-post pricing work?",
      a: "Each creator sets their own net price per post, from €20 up to the platform limit of €1,500, and can offer multi-post bundles at a discount. You pay that fixed price per published post through the platform. There is no cost per click, no CPM and no retainer on the self-serve plan.",
    },
    {
      q: "How does attribution work?",
      a: "Every creator gets a unique tracked link per post, and an optional pixel on your site ties each click, lead, pipeline and revenue event back to the exact creator and post. Your results dashboard shows impressions, clicks, leads and pipeline per creator, alongside marketplace benchmarks.",
    },
    {
      q: "Do you handle creator payouts?",
      a: "Yes. You approve content and pay every creator in one click. Contracts, invoices and payouts are handled by Naano through Stripe Connect, and creators are paid within 24 hours of a post going live.",
    },
    {
      q: "What's the difference between Free and Done for you?",
      a: "Self-serve is €0 per month: you run the marketplace, briefs, tracking and payouts yourself and only pay per published post. Managed campaigns are €700 per month plus post spend: the Naano team handles strategy, creator sourcing, briefs, launch and reporting for you.",
    },
    {
      q: "Can I upgrade or cancel anytime?",
      a: "Yes. Plans are month-to-month. You can upgrade, downgrade or cancel at any time, and campaign spend is always separate from the plan.",
    },
  ],
} as const;

export const CTA = {
  eyebrow: "Ready to launch?",
  title: "Your next creator campaign starts here.",
  sub: "Get a clear creator strategy, campaign format and estimated budget for your next launch.",
  cardEyebrow: "Campaign strategy call",
  cardTitle: "30-minute working session",
  cardBody: "Leave with a concrete plan for your next creator campaign.",
  bullets: ["Creator strategy", "Campaign format", "Budget recommendation"],
  button: { href: "/register/brand", label: "Book a strategy call" },
  buttonNote: "Create your workspace first; you pick a time from Book a call.",
  alt: { text: "Prefer to start yourself?", href: "/register/brand", label: "Start for free" },
  footnote: "Trusted by B2B teams building creator-led acquisition.",
} as const;
