"use client";

import { useState } from "react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

import { BRAND } from "@/config/brand";
type Row = { creatorId: string; name: string; avatarUrl: string; impressions: number; posts: number; clicks: number };
type Metric = "impressions" | "posts";

const METRICS: Array<{ key: Metric; label: string; unit: string }> = [
  { key: "impressions", label: "Estimated impressions", unit: `estimated ${BRAND.name} impressions` },
  { key: "posts", label: "Posts", unit: "sponsored posts" },
];

// naano's leaderboard with its "Estimated impressions | Posts" toggle.
export function Leaderboard({ rows }: { rows: Row[] }) {
  const [metric, setMetric] = useState<Metric>("impressions");
  const sorted = [...rows].sort((a, b) => b[metric] - a[metric]);
  const max = Math.max(1, ...sorted.map((r) => r[metric]));
  return (
    <section className="rounded-2xl border bg-background p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="font-semibold">{BRAND.name} campaign leaderboard</h2>
          <p className="text-sm text-muted-foreground">Estimated impressions generated by sponsored posts published for {BRAND.name} brand collaborations.</p>
        </div>
        <div role="group" aria-label="Metric" className="inline-flex rounded-lg border p-0.5 text-xs font-semibold">
          {METRICS.map((m) => (
            <button
              key={m.key}
              type="button"
              aria-pressed={metric === m.key}
              onClick={() => setMetric(m.key)}
              className="rounded-md px-3 py-1.5 text-muted-foreground aria-pressed:bg-foreground aria-pressed:text-background"
            >
              {m.label}
            </button>
          ))}
        </div>
      </div>
      {sorted.length === 0 ? (
        <p className="mt-4 text-sm text-muted-foreground">No published sponsored posts yet.</p>
      ) : (
        <ol className="mt-4 grid gap-2">
          {sorted.map((r, i) => (
            <li key={r.creatorId} className="flex items-center gap-3">
              <span className="w-6 text-center text-sm font-semibold text-muted-foreground">{i + 1}</span>
              <Avatar className="size-9">
                <AvatarImage src={r.avatarUrl} alt="" />
                <AvatarFallback>{r.name.charAt(0)}</AvatarFallback>
              </Avatar>
              <span className="w-40 min-w-0 truncate text-sm font-medium">{r.name}</span>
              <span className="h-2 flex-1 rounded-full bg-muted">
                <span className="animate-fill block h-2 rounded-full bg-brand transition-[width] duration-300" style={{ width: `${Math.round((r[metric] / max) * 100)}%` }} />
              </span>
              <span className="w-32 text-right text-sm">
                <span className="font-semibold">{r[metric].toLocaleString("en-US")}</span>
                <span className="block text-[10px] text-muted-foreground">{METRICS.find((m) => m.key === metric)?.unit} · {r.clicks} clicks</span>
              </span>
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}
