import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

type Row = { creatorId: string; name: string; avatarUrl: string; impressions: number; posts: number; clicks: number };

export function Leaderboard({ rows }: { rows: Row[] }) {
  const max = Math.max(1, ...rows.map((r) => r.impressions));
  return (
    <section className="rounded-2xl border bg-background p-5">
      <h2 className="font-semibold">Naano campaign leaderboard</h2>
      <p className="text-sm text-muted-foreground">Estimated impressions generated by sponsored posts published for Naano brand collaborations.</p>
      {rows.length === 0 ? (
        <p className="mt-4 text-sm text-muted-foreground">No published sponsored posts yet.</p>
      ) : (
        <ol className="mt-4 grid gap-2">
          {rows.map((r, i) => (
            <li key={r.creatorId} className="flex items-center gap-3">
              <span className="w-6 text-center text-sm font-semibold text-muted-foreground">{i + 1}</span>
              <Avatar className="size-9">
                <AvatarImage src={r.avatarUrl} alt="" />
                <AvatarFallback>{r.name.charAt(0)}</AvatarFallback>
              </Avatar>
              <span className="w-40 min-w-0 truncate text-sm font-medium">{r.name}</span>
              <span className="h-2 flex-1 rounded-full bg-muted">
                <span className="block h-2 rounded-full bg-brand" style={{ width: `${Math.round((r.impressions / max) * 100)}%` }} />
              </span>
              <span className="w-28 text-right text-sm">
                <span className="font-semibold">{r.impressions.toLocaleString("en-US")}</span>
                <span className="block text-[10px] text-muted-foreground">{r.posts} posts · {r.clicks} clicks</span>
              </span>
            </li>
          ))}
        </ol>
      )}
    </section>
  );
}
