import type { Metadata } from "next";
import { CaseStudySection } from "@/features/public/components/landing/CaseStudySection";
import { FaqSection } from "@/features/public/components/landing/FaqSection";
import { HeroSection } from "@/features/public/components/landing/HeroSection";
import { HowItWorksSection } from "@/features/public/components/landing/HowItWorksSection";
import { MarketplaceShowcase } from "@/features/public/components/landing/MarketplaceShowcase";
import { PostExamplesSection } from "@/features/public/components/landing/PostExamplesSection";
import { PricingSection } from "@/features/public/components/landing/PricingSection";
import { QuoteSection } from "@/features/public/components/landing/QuoteSection";
import { ResultsSection } from "@/features/public/components/landing/ResultsSection";
import { PublicFooter } from "@/features/public/components/nav/PublicFooter";
import { PublicNav } from "@/features/public/components/nav/PublicNav";
import { CtaSection } from "@/features/public/components/shared/CtaSection";
import { getShowcaseCreators, getTopPosts } from "@/features/public/server/queries";

export const metadata: Metadata = {
  title: "naano — The B2B LinkedIn Creator Marketplace",
  description: "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
};

// Reads the seeded creators/posts at request time so a missing database
// degrades to the static sections instead of failing the build.
export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [creators, posts] = await Promise.all([getShowcaseCreators(), getTopPosts()]);
  return (
    <>
      <PublicNav />
      <main className="flex-1">
        <HeroSection />
        <QuoteSection />
        <MarketplaceShowcase creators={creators} />
        <HowItWorksSection />
        <CaseStudySection />
        <ResultsSection />
        <PostExamplesSection posts={posts} />
        <PricingSection />
        <FaqSection />
        <CtaSection />
      </main>
      <PublicFooter />
    </>
  );
}
