import type { Metadata } from "next";
import { Reveal } from "@/components/motion/Reveal";
import { CaseStudySection } from "@/features/public/components/landing/CaseStudySection";
import { ScrollHero } from "@/features/public/components/hero/ScrollHero";
import { FaqSection } from "@/features/public/components/landing/FaqSection";
import { SayHeySection } from "@/features/public/components/gaze-footer/SayHeySection";
import { InkFooter } from "@/features/public/components/ink-footer/InkFooter";
import { HowItWorksSection } from "@/features/public/components/landing/HowItWorksSection";
import { MarketplaceShowcase } from "@/features/public/components/landing/MarketplaceShowcase";
import { PerformanceStage } from "@/features/public/components/performance/PerformanceStage";
import { PostExamplesSection } from "@/features/public/components/landing/PostExamplesSection";
import { PricingSection } from "@/features/public/components/landing/PricingSection";
import { QuoteSection } from "@/features/public/components/landing/QuoteSection";
import { PublicAssistantPill } from "@/features/public/components/nav/PublicAssistantPill";
import { PublicNav } from "@/features/public/components/nav/PublicNav";
import { LandingSplash } from "@/features/public/components/splash/LandingSplash";
import { CtaSection } from "@/features/public/components/shared/CtaSection";
import { getShowcaseCreators, getTopPosts } from "@/features/public/server/queries";

import { BRAND } from "@/config/brand";
export const metadata: Metadata = {
  title: `${BRAND.wordmark} — The B2B LinkedIn Creator Marketplace`,
  description: "Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.",
};

// Reads the seeded creators/posts at request time so a missing database
// degrades to the static sections instead of failing the build.
export const dynamic = "force-dynamic";

export default async function HomePage() {
  const [creators, posts] = await Promise.all([getShowcaseCreators(), getTopPosts()]);
  return (
    <>
      {/* First visit per tab: the splash covers the hero preload (no "LOADING 0%" first paint). */}
      <LandingSplash />
      <PublicNav />
      <main className="flex-1">
        <ScrollHero />
        <Reveal><QuoteSection /></Reveal>
        <Reveal><MarketplaceShowcase creators={creators} /></Reveal>
        <Reveal><HowItWorksSection /></Reveal>
        <Reveal><CaseStudySection /></Reveal>
        {/* Results = the metric-cards stage (docs/reference/metric-cards-spec.md); it runs its own entrance. */}
        <PerformanceStage />
        <Reveal><PostExamplesSection posts={posts} /></Reveal>
        <Reveal><PricingSection /></Reveal>
        <Reveal><FaqSection /></Reveal>
        <Reveal><CtaSection /></Reveal>
        {/* The gaze-scrub character as a section (docs/reference/gaze-footer-spec.md), the ink footer follows. */}
        <SayHeySection />
      </main>
      {/* The ink footer (docs/reference/ink-footer-spec.md); its cream/ink tokens live on .site-footer. */}
      <InkFooter />
      <PublicAssistantPill />
    </>
  );
}
